baseURL = 'https://kbabuji.com/'
languageCode = 'en-us'
title = 'kbabuji'
theme = 'minimal'
timezone = 'America/Chicago'
enableRobotsTXT = true

[params]
  title = 'kbabuji'
  description = "A software engineer's field notes from the frontier, where we peel back the layers of complex systems to reveal their hidden elegance."
  math = false
  [params.contact]
    email = 'krishna.pingal@gmail.com'
  [params.giscus]
    repo = "krispingal/krispingal.github.io"
    repoID = "R_kgDONNB2Ng"
    category = "Announcements"
    categoryID = "DIC_kwDONNB2Ns4CmciE"
    mapping = "url"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "catppuccin_latte"
    lang = "en"
    loading = "lazy"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-macchiato'
    tabWidth = 4

[sitemap]
  changeFreq = 'monthly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1



[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']


