baseURL = 'https://kbabuji.com/'
locale = 'en-us'
title = 'kbabuji'
theme = 'minimal'
timezone = 'America/Chicago'
enableRobotsTXT = true

[params]
  title = 'kbabuji'
  description = "A software engineer's field notes from the frontier, where we peel back the layers of complex systems to reveal their hidden elegance."
  math = false
  mainSection = "articles"
  startYear = 2016
  googleFontsURL = "https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600&display=swap"
  # --- JSON-LD AUTHOR/PUBLISHER HARDCODING ---
  author = "Krishna Babuji" # Default author name (for author.name)
  authorUrl = "about" # URL to your about page (for author.url)
  authorImage = "about/images/portrait.webp" # Path to your author avatar (for author.image)
  logo = "/favicon-32x32.png" # Path to your organization logo (for publisher.logo.url)
  # ------------------------------------------
  [params.contact]
    email = 'krishna.pingal@gmail.com'
  [[params.social]]
    name = "github"
    label = "GitHub"
    url = "https://github.com/krispingal"
  [[params.social]]
    name = "linkedin"
    label = "LinkedIn"
    url = "https://linkedin.com/in/krishna-babuji"
  [[params.social]]
    name = "email"
    label = "Email"
    url = "mailto:krishna.pingal@gmail.com"
  [[params.social]]
    name = "rss"
    label = "RSS"
    url = "/articles/index.xml"
  [params.giscus]
    repo = "krispingal/krispingal.github.io"
    repoID = "R_kgDONNB2Ng"
    category = "Announcements"
    categoryID = "DIC_kwDONNB2Ns4CmciE"
    mapping = "url"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "catppuccin_macchiato"
    lang = "en"
    loading = "lazy"

[[menus.main]]
  name = "About"
  pageRef = "/about"
  weight = 10

[[menus.main]]
  name = "Archives"
  pageRef = "/articles"
  weight = 20

[[menus.main]]
  name = "Categories"
  pageRef = "/categories"
  weight = 30

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 40

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-macchiato'
    tabWidth = 4

[sitemap]
  changeFreq = 'monthly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1



[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']


