baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'kbabuji'
theme = 'minimal'
timezone = 'America/Chicago'
enableRobotsTXT = true

[params]
  math = false
  [params.contact]
    email = 'krishna.pingal@gmail.com'

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10


[sitemap]
  changeFreq = 'monthly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1
