baseURL = 'https://example.org/'
locale = 'en-US'
title = 'Untangling thoughts'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
        [markup.goldmark.renderhooks.image]
          enableDefault = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.158.0"
